development:
  adapter: sqlite3
  encoding: unicode
  database: database
  pool: 5
  username: admin
  password:
  
production:
  adapter: postgresql
  encoding: unicode
  database: database
  pool: 5
  username: admin
  password: